#check if you have correct java in ec2, if no install sudo yum install java-1.8.0-amazon-corretto-devel, sudo amazon-linux-extras install java-openjdk11
#sudo update-alternatives --config java selcet latest java and then run the palybook
---
- name: Install Jenkins on EC2 instance
  hosts: jenkins
  become: yes

  tasks:
    - name: Install Java (OpenJDK 8) 
      yum:
        name: java-1.8.0-openjdk-devel
        state: present

    - name: Add Jenkins repo
      yum_repository:
        name: jenkins
        description: Jenkins repo
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        gpgcheck: yes
        enabled: yes

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

  gather_facts: no
