# provision postgre 2 ec2 instance
---
- hosts: all
  become: yes
  vars_files:
    - secrets.yml
  tasks:
    - name: Install PostgreSQL
      package:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL user and database
      postgresql_user:
        name: myuser
        password: "{{ postgresql_password }}"
        role_attr_flags: CREATEDB
        state: present
        no_log: true

    - name: Create a PostgreSQL database
      postgresql_db:
        name: mydb
        owner: myuser
